---
apiVersion: v1
kind: ConfigMap
metadata:
  name: smoke-test-config
  namespace: default
data:
  index.html: |
    <html>
    <h2>Hello world 1!!</h2>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smoke-test-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        testService: smoke-test
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - name: smoke-test-index-config
          mountPath: /usr/share/nginx/html
      volumes:
      - name: smoke-test-index-config
        configMap:
          name: smoke-test-config
---
apiVersion: v1
kind: Service
metadata:
  name: smoke-test-service-nodeport
spec:
  selector:
    app: nginx
    testService: smoke-test
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30081
---
apiVersion: v1
kind: Service
metadata:
  name: smoke-test-service-lb
spec:
  selector:
    app: nginx
    testService: smoke-test
  type: LoadBalancer
  # loadBalancerIP is optional. MetalLB will automatically allocate an IP
  # from its pool if not specified. You can also specify one manually.
  # loadBalancerIP: x.y.z.a
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
